### ISSUE TITLE
Training problems with the code

### ISSUE THREAD

**Issue by 2490o** [Hongbin98/MonoTTA#2]
Is the code provided now only for evaluation and not for training?

**Comment by Hongbin98** [comment]
Thanks for your attention to our work~
We have provided the **training** cmd `CUDA_VISIBLE_DEVICES=0 python tools/tta_monotta.py --config runs/monoflex.yaml --ckpt model_moderate_best_soft.pth --eval --output kitti-c/gaussian1` of MonoTTA.
If you have any questions, please feel free to ask.

**Comment by 2490o** [comment]
Running the above commands only evaluates, it does not train
![image](https://github.com/user-attachments/assets/19aa5fad-54cf-4fb0-9d64-810955464dd3)

**Comment by Hongbin98** [comment]
MonoTTA follows a new adaptation paradigm termed **Fully Test-time Adaptation** which aims to adapt a well-trained model to unlabeled test data by handling potential data distribution shifts at **test time**.
So MonoTTA would adapt the well-trained model at the inference stage (before providing the final prediction). 
If you are still confused, you may check the related work (Fully Test-time Adaptation methods) in classification tasks~
