### ISSUE TITLE
ERROR: Failed building wheel for inplace-abn

### ISSUE THREAD

**Issue by heegwang27** [Hongbin98/MonoTTA#3]
I am using your Docker environment, but I encountered an error. 
Has this issue been resolved?

![image](https://github.com/user-attachments/assets/c72ae765-6f1a-45b0-a2c0-b21d3ceab8e9)

**Comment by Hongbin98** [comment]
Sorry for my late reply.

Could you try to build this environment in conda? 
Providing more info, like your Cuda version and the type of GPU would be helpful.
